# Generated by Django 3.1.2 on 2021-05-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
